version: 0.2

phases:
  install:
    commands:
      - echo Installing prerequisites...
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID
      - AWS_REGION=$AWS_DEFAULT_REGION
      - curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.27.6/2023-10-17/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - mkdir -p ~/.kube
      - echo Setting up kubeconfig for EKS...
      - aws eks --region ap-northeast-2 update-kubeconfig --name ticket101-cluster
      - echo Verifying Kubernetes access...
      - kubectl get pods --all-namespaces
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 205930629963.dkr.ecr.ap-northeast-2.amazonaws.com
      - echo Pre-build step completed.
      - export FRONTEND_URL=$(aws ssm get-parameter --name "FRONTEND_URL" --with-decryption --query "Parameter.Value" --output text)
      - echo env parameter FRONTEND_URL... $FRONTEND_URL

      - export ACCESS_KEY_ID=$(aws ssm get-parameter --name "ACCESS_KEY_ID" --with-decryption --query "Parameter.Value" --output text)
      - echo env parameter ACCESS_KEY_ID... $ACCESS_KEY_ID

      - export SECRET_ACCESS_KEY=$(aws ssm get-parameter --name "SECRET_ACCESS_KEY" --with-decryption --query "Parameter.Value" --output text)
      - echo env parameter SECRET_ACCESS_KEY... $SECRET_ACCESS_KEY

      - kubectl delete secret app-secrets2 || true
      - kubectl create secret generic app-secrets2 --from-literal=ACCESS_KEY_ID=$ACCESS_KEY_ID --from-literal=SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY --from-literal=FRONTEND_URL=$FRONTEND_URL
  build:
    commands:
      commands:
      - echo Building and pushing Docker images to ticket101-ecr...

      - echo Building auth service...
      - docker build --no-cache -t ticket101-ecr:auth-latest --build-arg ACCESS_KEY_ID=$ACCESS_KEY_ID --build-arg SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY --build-arg FRONTEND_URL=$FRONTEND_URL ./backend/auth
      - docker tag ticket101-ecr:auth-latest 205930629963.dkr.ecr.ap-northeast-2.amazonaws.com/ticket101-ecr:auth-latest
      - docker push 205930629963.dkr.ecr.ap-northeast-2.amazonaws.com/ticket101-ecr:auth-latest

      - echo Building favorite service...
      - docker build --no-cache -t ticket101-ecr:favorite-latest --build-arg ACCESS_KEY_ID=$ACCESS_KEY_ID --build-arg SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY --build-arg ACCESS_KEY_ID=$ACCESS_KEY_ID --build-arg SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY --build-arg FRONTEND_URL=$FRONTEND_URL ./backend/favorite
      - docker tag ticket101-ecr:favorite-latest 205930629963.dkr.ecr.ap-northeast-2.amazonaws.com/ticket101-ecr:favorite-latest
      - docker push 205930629963.dkr.ecr.ap-northeast-2.amazonaws.com/ticket101-ecr:favorite-latest

      - echo Building performance service...
      - docker build --no-cache -t ticket101-ecr:performance-latest --build-arg ACCESS_KEY_ID=$ACCESS_KEY_ID --build-arg SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY --build-arg FRONTEND_URL=$FRONTEND_URL ./backend/performance
      - docker tag ticket101-ecr:performance-latest 205930629963.dkr.ecr.ap-northeast-2.amazonaws.com/ticket101-ecr:performance-latest
      - docker push 205930629963.dkr.ecr.ap-northeast-2.amazonaws.com/ticket101-ecr:performance-latest

      - echo Building search service...
      - docker build --no-cache -t ticket101-ecr:search-latest --build-arg ACCESS_KEY_ID=$ACCESS_KEY_ID --build-arg SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY --build-arg FRONTEND_URL=$FRONTEND_URL ./backend/search
      - docker tag ticket101-ecr:search-latest 205930629963.dkr.ecr.ap-northeast-2.amazonaws.com/ticket101-ecr:search-latest
      - docker push 205930629963.dkr.ecr.ap-northeast-2.amazonaws.com/ticket101-ecr:search-latest

      - echo Building survey service...
      - docker build --no-cache -t ticket101-ecr:survey-latest --build-arg ACCESS_KEY_ID=$ACCESS_KEY_ID --build-arg SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY --build-arg FRONTEND_URL=$FRONTEND_URL ./backend/survey
      - docker tag ticket101-ecr:survey-latest 205930629963.dkr.ecr.ap-northeast-2.amazonaws.com/ticket101-ecr:survey-latest
      - docker push 205930629963.dkr.ecr.ap-northeast-2.amazonaws.com/ticket101-ecr:survey-latest
  post_build:
    commands:
     - echo Deploying auth service...
      - kubectl apply -f ./EKS/Deployment.yaml
      - kubectl apply -f ./EKS/Service.yaml
      - kubectl apply -f ./EKS/CronJob.yaml

artifacts:
  files:
    - EKS/Deployment.yaml
    - EKS/Service.yaml
    - EKS/CronJob.yaml
