version: 0.2

phases:
  install:
    commands:
      - echo Installing prerequisites...
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID
      - AWS_REGION=$AWS_DEFAULT_REGION
      - curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.27.6/2023-10-17/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - mkdir -p ~/.kube
      - echo Setting up kubeconfig for EKS...
      - aws eks --region ap-northeast-2 update-kubeconfig --name test3
      - echo Verifying Kubernetes access...
      - kubectl get pods --all-namespaces

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 205930629963.dkr.ecr.ap-northeast-2.amazonaws.com
      - echo Fetching parameters from AWS Systems Manager Parameter Store...
      - export REACT_APP_AWS_PROJECT_REGION=$(aws ssm get-parameter --name "REACT_APP_AWS_PROJECT_REGION" --with-decryption --query "Parameter.Value" --output text)
      - export REACT_APP_AWS_COGNITO_IDENTITY_POOL_ID=$(aws ssm get-parameter --name "REACT_APP_AWS_COGNITO_IDENTITY_POOL_ID" --with-decryption --query "Parameter.Value" --output text)
      - export REACT_APP_AWS_USER_POOLS_ID=$(aws ssm get-parameter --name "REACT_APP_AWS_USER_POOLS_ID" --with-decryption --query "Parameter.Value" --output text)
      - export REACT_APP_AWS_USER_POOLS_WEB_CLIENT_ID=$(aws ssm get-parameter --name "REACT_APP_AWS_USER_POOLS_WEB_CLIENT_ID" --with-decryption --query "Parameter.Value" --output text)
      - echo Creating Kubernetes Secrets...
      - kubectl create secret generic app-secrets \
          --from-literal=REACT_APP_AWS_PROJECT_REGION=$REACT_APP_AWS_PROJECT_REGION \
          --from-literal=REACT_APP_AWS_COGNITO_IDENTITY_POOL_ID=$REACT_APP_AWS_COGNITO_IDENTITY_POOL_ID \
          --from-literal=REACT_APP_AWS_USER_POOLS_ID=$REACT_APP_AWS_USER_POOLS_ID \
          --from-literal=REACT_APP_AWS_USER_POOLS_WEB_CLIENT_ID=$REACT_APP_AWS_USER_POOLS_WEB_CLIENT_ID || echo "Secret already exists, skipping."
      - echo Pre-build step completed.

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t test2:latest .
      - docker tag test2:latest 205930629963.dkr.ecr.ap-northeast-2.amazonaws.com/test2:latest
      - echo Pushing Docker image to ECR...
      - docker push 205930629963.dkr.ecr.ap-northeast-2.amazonaws.com/test2:latest

  post_build:
    commands:
      - echo Deploying application to EKS...
      - export AWS_ECR_URI=205930629963.dkr.ecr.ap-northeast-2.amazonaws.com/test2:latest
      - sed -i.bak 's#AWS_ECR_URI#'"$AWS_ECR_URI"'#g' ./EKS/Deployment.yaml
      - kubectl apply -f ./EKS/Deployment.yaml
      - kubectl apply -f ./EKS/Service.yaml
      - echo Deployment completed on $(date).
