apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crawler-app
  template:
    metadata:
      labels:
        app: crawler-app
    spec:
      containers:
      - name: crawler-app
        image: 205930629963.dkr.ecr.ap-northeast-2.amazonaws.com/test2:latest
        ports:
        - containerPort: 80
