apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-crawler
  namespace: default
  labels:
    app: eks-test
    environment: production
    version: v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-test
  template:
    metadata:
      labels:
        app: eks-test
    spec:
      nodeSelector:
          role: backend
      containers:
        - name: eks-test
          image: 205930629963.dkr.ecr.ap-northeast-2.amazonaws.com/ticket101-ecr:auth-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5007
          env:
            - name: AWS_REGION
              value: ap-northeast-2 # 적절한 AWS 리전 값
            - name: ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets2
                  key: ACCESS_KEY_ID
            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets2
                  key: SECRET_ACCESS_KEY
