apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: AWS_ECR_URI # CodeBuild에서 실제 이미지 URL로 치환
          ports:
            - containerPort: 80
          imagePullPolicy: Always # 항상 최신 이미지를 가져옴
          env:
            - name: DATE
              value: DATE_STRING # CodeBuild에서 현재 날짜로 치환
          command:
            - sh
            - -c
            - |
              export REACT_APP_AWS_PROJECT_REGION=$(aws ssm get-parameter --name "REACT_APP_AWS_PROJECT_REGION" --with-decryption --query "Parameter.Value" --output text) &&
              export REACT_APP_AWS_COGNITO_IDENTITY_POOL_ID=$(aws ssm get-parameter --name "REACT_APP_AWS_COGNITO_IDENTITY_POOL_ID" --with-decryption --query "Parameter.Value" --output text) &&
              export REACT_APP_AWS_USER_POOLS_ID=$(aws ssm get-parameter --name "REACT_APP_AWS_USER_POOLS_ID" --with-decryption --query "Parameter.Value" --output text) &&
              export REACT_APP_AWS_USER_POOLS_WEB_CLIENT_ID=$(aws ssm get-parameter --name "REACT_APP_AWS_USER_POOLS_WEB_CLIENT_ID" --with-decryption --query "Parameter.Value" --output text) &&
              exec your-app-command
