apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"  # ALB 생성 지정
    service.beta.kubernetes.io/aws-load-balancer-internal: "false" # 인터넷 노출 여부
spec:
  ports:
    - name: "http"
      protocol: TCP
      port: 80         # 외부에서 접근하는 포트
      targetPort: 80   # 컨테이너에서 노출하는 포트
  selector:
    app: frontend      # Deployment의 selector와 일치해야 함
  type: LoadBalancer
